---
version: "2.0"

services:
  ai-app:
    image: docker image
    expose:
      - port: 5000
        as: 5000
        to:
          - global: true
    env:
      - FLASK_ENV=production
      - HUGGINGFACE_TOKEN=

profiles:
  compute:
    ai-app:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 10Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:

  placement:
    akash:
      pricing:
        ai-app:
          denom: uakt
          amount: 1000
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      attributes:
        host: akash

deployment:
  ai-app:
    akash:
      profile: ai-app
      count: 1
